export enum OptimisticLockMode {
  OPTIMISTIC = 'OPTIMISTIC',
}

export enum PessimisticLockMode {
  PESSIMISTIC_READ = 'PESSIMISTIC_READ',
  PESSIMISTIC_WRTIE = 'PESSIMISTIC_WRTIE',
  DIRTY_READ = 'DIRTY_READ',
  PESSIMISTIC_PARTIAL_WRITE = 'PESSIMISTIC_PARTIAL_WRITE',
  PESSIMISTIC_WRITE_OR_FAIL = 'PESSIMISTIC_WRITE_OR_FAIL',
  FOR_NO_KEY_UPDATE = 'FOR_NO_KEY_UPDATE',
  FOR_KEY_SHARE = 'FOR_KEY_SHARE',
}
