export enum ErrorCode {
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  INVALID_TOKEN = 'INVALID_TOKEN',
  TOKEN_NOT_PROVIDED = 'TOKEN_NOT_PROVIDED',
  UNAUTHORIZED_USER = 'UNAUTHORIZED_USER',
  INVALID_INPUT = 'INVALID_INPUT',
  OPTIMISTIC_LOCK_CONFLICT = 'OPTIMISTIC_LOCK_CONFLICT',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  NOT_EXISTED_BUCKET = 'NOT_EXISTED_BUCKET',
}
